url: https://jhbsouthstake.github.io
baseurl: /

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Site settings
title: Johannesburg South Stake
email: your-email@domain.com
description: "Johannesburg South Stake of the Church of Jesus Christ of Latter-day Saint, Come Unto Christ"


# Team names, titles and social links
people:
- name: Sandile Makasi
  pic: 1Makasi.png
  position: Stake President
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Olev Taim
  pic: 2Taim.png
  position: 1st Counselor
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Lerato Slater
  pic: 3Slater.png
  position: 2nd Counselor
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

congregations:
- name: Ennerdale Branch
  pic: ennerdale.png
  address:
    - line: 41 Fourth Avenue
    - line: Mid-Ennerdale
    - line: Johannesburg
  meeting-time: Sunday 9:00 AM
  map-link: https://maps.app.goo.gl/MaUfqQVisXgaiYc46

- name: Florida 1st Ward
  pic: florida.png
  address:
    - line: c/o Philips Ave & Gildea Str
    - line: Discovery
    - line: Roodepoort
  meeting-time: Sunday 9:00 AM
  map-link: https://maps.app.goo.gl/uhMB4Acvek9bvFBP8

- name: Florida 2nd Ward
  pic: florida.png
  address:
    - line: c/o Philips Ave & Gildea Str
    - line: Discovery
    - line: Roodepoort
  meeting-time: Sunday 11:00 AM
  map-link: https://maps.app.goo.gl/uhMB4Acvek9bvFBP8

- name: Orange Farm Branch
  pic: orange-farm.png
  address:
    - line: Orange Farm Primary School
    - line: Orange Farm
  meeting-time: Sunday 9:00 AM
  map-link: https://maps.app.goo.gl/R96iJpjiKWsjSFaQ7

- name: Randburg Ward
  pic: randburg.png
  address:
    - line: 145 Curzon Rd
    - line: Cramerview
    - line: Sandton
  meeting-time: Sunday 10:30 AM
  map-link: https://maps.app.goo.gl/bBUjutc78goxMc7YA

- name: Ridgeway Ward
  pic: ridgeway.png
  address:
    - line: Cnr Susanna Str & Swartgoud Str
    - line: Ridgeway
    - line: Johannesburg
  meeting-time: Sunday 9:00 AM
  map-link: https://maps.app.goo.gl/iRHHiKeRwBNXpUJg8

- name: Sebokeng Ward
  pic: sebokeng.png
  address:
    - line: Erf 62390
    - line: Zone 17
    - line: Sebokeng
  meeting-time: Sunday 9:00 AM
  map-link: https://maps.app.goo.gl/T52TE4oFGXNKLfEg9

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: youtube
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Cnr Philips Ave & Gildea Str
  - line: Discovery
  - line: Roodepoort
  - line: Gauteng
  - line: South Africa
  - line: -26.152264, 27.893879

# Build settings
markdown: kramdown
permalink: pretty
