url: https://jhbsouthstake.github.io
baseurl: /

# Site settings
title: Johannesburg South Stake
email: your-email@domain.com
description: "Johannesburg South Stake of the Church of Jesus Christ of Latter-day Saint, Come Unto Christ"


# Team names, titles and social links
people:
- name: Sandile Makasi
  pic: 1Makasi.png
  position: Stake President
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Olev Taim
  pic: 2Taim.png
  position: 1st Counselor
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Lerato Slater
  pic: 3Slater.png
  position: 2nd Counselor
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

congregations:
- name: Ennerdale Branch
  pic: ennerdale.png
  address:
    - line: 41 Fourth Avenue
    - line: Mid-Ennerdale
    - line: Johannesburg
  meeting-time: Sunday 9:00 AM

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: youtube
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Cnr Philips Ave & Gildea Str
  - line: Discovery
  - line: Roodepoort
  - line: Gauteng
  - line: South Africa
  - line: -26.152264, 27.893879

# Build settings
markdown: kramdown
permalink: pretty
