url: https://jhbsouthstake.github.io
baseurl: /

# Site settings
title: Johannesburg South Stake
email: your-email@domain.com
description: "Johannesburg South Stake of the Church of Jesus Christ of Latter-day Saint, Come Unto Christ"


# Team names, titles and social links
people:
- name: Sandile Makasi
  pic: 1
  position: Stake President
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Olev Taim
  pic: 2
  position: 1st Counselor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Lerato Slater
  pic: 3
  position: 2nd Counselor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: youtube
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Cnr Philips Ave & Gildea Str
  - line: Discovery
  - line: Roodepoort
  - line: Gauteng
  - line: South Africa
  - line: -26.152264, 27.893879

# Build settings
markdown: kramdown
permalink: pretty
